### ISSUE TITLE
Cannot change country code on edit page

### ISSUE THREAD

**Issue by salmanhijazi** [YieldStudio/nova-phone-field#1]
Hello, 

On the edit page if the field is pre-filled, you cannot change the country code by simply backspacing or selecting all and pressing delete. To be able to, you have to go behind the 1st or 2nd digit of the country code and press delete to be able to change it.

Not sure what is the problem, but can you please check?

Thanks!

**Comment by JamesHemery** [comment]
Hi @salmanhijazi ,

Actually, we have not identified the cause of this problem. As this is not a critical issue, we do not plan to invest any research in the coming days.

But we are open to review/merge a PR :)

**Comment by JamesHemery** [comment]
Fixed in 2.0.0 : https://github.com/YieldStudio/nova-phone-field/releases/tag/2.0.0
