### ISSUE TITLE
Make field copyable

### ISSUE THREAD

**Issue by AndreSchwarzer** [YieldStudio/nova-phone-field#3]
I'd would be a nice addtion if the field could be marked as copyable, as text and email fields for example.

[https://nova.laravel.com/docs/4.0 `->copyable()`](https://nova.laravel.com/docs/4.0/resources/fields.html#copying-text-field-values-to-the-clipboard)

<img width="146" alt="Screenshot 2023-01-08 at 19 47 54" src="https://user-images.githubusercontent.com/6991100/211213510-5992a0a1-08f3-4f80-8ef6-c2c02ce7cb24.png">

**Comment by JamesHemery** [comment]
Hi @AndreSchwarzer,

I'll be happy to review a PR again that adds this option :)

**Comment by muhammadsaeedparacha** [comment]
Lovely package. I'll have a dev add this functionality in a day or two

**Comment by JamesHemery** [comment]
Released in 2.0.0 : https://github.com/YieldStudio/nova-phone-field/releases/tag/2.0.0
