### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by exshapoval** [YieldStudio/nova-phone-field#5]
Hi, I use
Laravel 10
Nova 4
your plugin

And after install I see console error and don't see field

![iScreen Shoter - Firefox - 230306132127](https://user-images.githubusercontent.com/71822953/223097193-a5c5a743-2890-4210-b7a6-6f6aeb50523c.jpg)

![iScreen Shoter - Firefox - 230306132113](https://user-images.githubusercontent.com/71822953/223097243-4e76027b-f643-43d0-b81b-6449035a09ef.jpg)

**Comment by LintonAchmad** [comment]
Same issue

**Comment by JamesHemery** [comment]
Can you try 2.0.0 : https://github.com/YieldStudio/nova-phone-field/releases/tag/2.0.0 ?
