### ISSUE TITLE
Field not working with Dynamic Field Methods on Nova 4

### ISSUE THREAD

**Issue by MarcosGit** [YieldStudio/nova-phone-field#7]
This field only work in fields method and not working in Dynamic Field Methods

**Comment by JamesHemery** [comment]
Hi @MarcosGit 
I'll check next week, if you want I can review a PR..

**Comment by JamesHemery** [comment]
Can you try 2.0.0 : https://github.com/YieldStudio/nova-phone-field/releases/tag/2.0.0 ?

**Comment by MarcosGit** [comment]
ok i will try this version
